export const SET_PIZZA_NAME = "SET_PIZZA_NAME";
export const SET_PIZZA_DOUGH = "SET_PIZZA_DOUGH";
export const SET_PIZZA_SIZE = "SET_PIZZA_SIZE";
export const SET_PIZZA_SAUCE = "SET_PIZZA_SAUCE";
export const CHANGE_INGREDIENT_COUNT = "CHANGE_INGREDIENT_COUNT";
export const RESET_BUILDER_STATE = "RESET_BUILDER_STATE";
export const ADD_TO_CART = "ADD_TO_CART";
