export const UPDATE_ENTITY = "UPDATE_ENTITY";
export const DELETE_ENTITY = "DELETE_ENTITY";

// BUILDER
export const SET_PIZZA = "SET_PIZZA";
export const SET_INGREDIENTS = "SET_INGREDIENTS";
export const SET_PIZZA_PROPERTY = "SET_PIZZA_PROPERTY";
export const SET_BUILDER_LIST = "SET_BUILDER_LIST";
export const RESET_BUILDER_STATE = "RESET_BUILDER_STATE";
export const RESET_PIZZA_STATE = "RESET_PIZZA_STATE";
export const RESET_INGREDIENTS_STATE = "RESET_INGREDIENTS_STATE";
export const CHANGE_BUILDER_STATE = "CHANGE_BUILDER_STATE";
export const SET_INGREDIENT_COUNT = "SET_INGREDIENT_COUNT";

// CART
export const SET_ADDITIONAL_LIST = "SET_ADDITIONAL_LIST";
export const ADD_PIZZA_TO_CART = "ADD_TO_CART";
export const SET_ADDRESS_PROPERTY = "SET_ADDRESS_PROPERTY";
export const INCREMENT_PIZZA_QUANTITY = "INCREMENT_PIZZA_QUANTITY";
export const DECREMENT_PIZZA_QUANTITY = "DECREMENT_PIZZA_QUANTITY";
export const INCREMENT_ADDITIONAL_QUANTITY = "INCREMENT_ADDITIONAL_QUANTITY";
export const DECREMENT_ADDITIONAL_QUANTITY = "DECREMENT_ADDITIONAL_QUANTITY";
export const RESET_CART_STATE = "RESET_CART_STATE";
export const REPEAT_ORDER = "REPEAT_ORDER";
export const SET_ADDRESS = "SET_ADDRESS";
export const SET_PHONE = "SET_PHONE";

// AUTH
export const SET_USER = "SET_USER";
export const SET_IS_AUTHENTICATED = "SET_IS_AUTHENTICATED";

// ORDERS
export const SET_ORDERS = "SET_ORDERS";

// ADDRESSES
export const SET_ADDRESSES = "SET_ADDRESSES";

// NOTIFICATIONS
export const ADD_NOTIFICATION = "ADD_NOTIFICATION";
